export const FETCH_USER_LOADING = "FETCH_USER_LOADING";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAILURE = "FETCH_USER_FAILURE";

export const FETCH_RANDOM_USER_LOADING = "FETCH_RANDOM_USER_LOADING";
export const FETCH_RANDOM_USER_SUCCESS = "FETCH_RANDOM_USER_SUCCESS";
export const FETCH_RANDOM_USER_FAILURE = "FETCH_RANDOM_USER_FAILURE";

export const CLEAR_CURRENT_USER = "CLEAR_CURRENT_USER";
