// REDUX ACTION TYPES
export const TICK = "TICK";
export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";
export const RESET = "RESET";

export const FETCH_USER_LOADING = "FETCH_USER_LOADING";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAILURE = "FETCH_USER_FAILURE";

export const FETCH_FOLLOWERS_LOADING = "FETCH_FOLLOWERS_LOADING";
export const FETCH_FOLLOWERS_SUCCESS = "FETCH_FOLLOWERS_SUCCESS";
export const FETCH_FOLLOWERS_FAILURE = "FETCH_FOLLOWERS_FAILURE";

export const FETCH_REPOS_LOADING = "FETCH_REPOS_LOADING";
export const FETCH_REPOS_SUCCESS = "FETCH_REPOS_SUCCESS";
export const FETCH_REPOS_FAILURE = "FETCH_REPOS_FAILURE";

export const FETCH_COMMITS_LOADING = "FETCH_COMMITS_LOADING";
export const FETCH_COMMITS_SUCCESS = "FETCH_COMMITS_SUCCESS";
export const FETCH_COMMITS_FAILURE = "FETCH_COMMITS_FAILURE";

export const FETCH_RANDOM_USER_LOADING = "FETCH_RANDOM_USER_LOADING";
export const FETCH_RANDOM_USER_SUCCESS = "FETCH_RANDOM_USER_SUCCESS";
export const FETCH_RANDOM_USER_FAILURE = "FETCH_RANDOM_USER_FAILURE";
