export const FETCH_USER_LOADING: string = "FETCH_USER_LOADING";
export const FETCH_USER_SUCCESS: string = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAILURE: string = "FETCH_USER_FAILURE";

export const FETCH_RANDOM_USER_LOADING: string = "FETCH_RANDOM_USER_LOADING";
export const FETCH_RANDOM_USER_SUCCESS: string = "FETCH_RANDOM_USER_SUCCESS";
export const FETCH_RANDOM_USER_FAILURE: string = "FETCH_RANDOM_USER_FAILURE";

export const CLEAR_CURRENT_USER: string = "CLEAR_CURRENT_USER";
